spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  batch:
    initialize-schema: never

springdoc:
  swagger-ui:
    operations-sorter: method
    config-url: /api-docs
    disable-swagger-default-url: false
  show-actuator: true
  api-docs:
    path: /api-docs

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs

graphql:
  packages:
    - "com.dongholab.graphql"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000

server:
  port: 8080
---

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graphql?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: dongho135
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  r2dbc:
    url: r2dbc:mariadb://127.0.0.1:3306/graphql
    username: root
    password: dongho135
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
  config:
    activate:
      on-profile: local